### ISSUE TITLE
Make it possible to patch spec.providerConfigRef.name

### ISSUE THREAD

**Issue by markussiebert** [crossplane-contrib/x-generation#21]
If I understand the functions right, it's not possible now to create patches like:

```yaml
overrideFieldsInClaim:
  - claimPath: spec.claimRef.namespace
    managedPath: spec.providerConfigRef.name
```
It would be great if it would be possible.
