### ISSUE TITLE
handle multiple CRDs to build complex Compositions

### ISSUE THREAD

**Issue by DrummyFloyd** [crossplane-contrib/x-generation#34]
### What problem are you facing?

Would be cool to build for a composition based on multiple Crds
for instance

i want to create an azure Keyvault instance, with vault/keys/accessPolicies in the same times

- https://github.com/crossplane-contrib/provider-upjet-azure/blob/main/package/crds/keyvault.azure.upbound.io_accesspolicies.yaml
- https://github.com/crossplane-contrib/provider-upjet-azure/blob/main/package/crds/keyvault.azure.upbound.io_vaults.yaml
- https://github.com/crossplane-contrib/provider-upjet-azure/blob/main/package/crds/keyvault.azure.upbound.io_keys.yaml

this should look like this ..
```yaml
providers:  
  baseURL: https://raw.githubusercontent.com/crossplane-contrib/%s/%s/package/crds/%s
  name: provider-upjet-azure
  version: v1.4.0
  crd:s
    - file: keyvault.azure.upbound.io_vaults.yaml
      version: v1beta2
    - file: keyvault.azure.upbound.io_keys.yaml
      version: v1beta2
    - file: keyvault.azure.upbound.io_accesspolicies.yaml
      version: v1beta2
```

### How could Crossplane help solve your problem?

dunno, if it's feasible, or if the tools is designed for this
