### ISSUE TITLE
New local configuration for spec.defaultCompositeDeletePolicy

### ISSUE THREAD

**Issue by birapjr** [crossplane-contrib/x-generation#41]
As a cloud engineer, I want the codebase IaC to reflect the actual state in AWS.

Sometimes when claims get deleted but the managed resource fails to be deleted the claim and composite is gone, but the managed resource still exists. This happens a lot when databases are deleted but deletion protection is still set.

 

Using `defaultCompositeDeletePolicy`: `Foreground` claims one can configure compositions to not get removed from kubernetes until the managed resources got cleaned up properly. 

 
We would like x-generation tool to be able to add `spec.defaultCompositeDeletePolicy: Foreground` to the compositions that this feature was selected to apply.

What to implement:
- New `local configuration` called `defaultCompositeDeletePolicy` that accept the values: `Background` or `Foreground`
- Will create `spec.defaultCompositeDeletePolicy` on the composition with the value set on the `generate.yaml` file

Example `generate.yaml`:
```yaml
group: dms.aws.dkb.cloud
name: Endpoint
version: v1beta1
provider:
  baseURL: https://raw.githubusercontent.com/upbound/%s/%s/package/crds/%s
  name: provider-aws
  version: main
  crd:
    file: dms.aws.upbound.io_endpoints.yaml
    version: v1beta1
patchExternalName: false
defaultCompositeDeletePolicy: Foreground
compositions:
  - name: compositeendpoint.dms.aws.example
    provider: example
    default: true
```

Example output `definition.yaml`:
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeendpoints.dms.aws.example
spec:
  defaultCompositeDeletePolicy: Foreground
  claimNames:
    kind: Endpoint
    plural: endpoints
  defaultCompositionRef:
    name: compositeendpoint.dms.aws.example
  group: dms.aws.dkb.example
....
```
