### ISSUE TITLE
The local configuration defaultCompositeDeletePolicy only works for not pipeline compositions

### ISSUE THREAD

**Issue by birapjr** [crossplane-contrib/x-generation#50]
### What happened?

The new local configuration `defaultCompositeDeletePolicy` only works for not pipeline compositions. If the gererator-config.yaml flag `usePipeline` is set to `false` the code to add the defaultCompositeDeletePolicy property to the `xrd` is not called.

### How can we reproduce it?
Generate a composition with:
- gererator-config.yaml flag `usePipeline` is set to `true`
-  the `generate.yaml` set the local configuration `defaultCompositeDeletePolicy` to `Foreground`
- execute the generation, the `defaultCompositeDeletePolicy: Foreground` will not be added to the outputed xrd `definition.yaml`

### What environment did it happen in?
Crossplane version: 1.18.3
x-generation: 0.11.0

Sample configuration:

generator-config.yaml
```yaml
compositionIdentifier: example.cloud
provider:
  baseURL: https://raw.githubusercontent.com/crossplane-contrib/%s/%s/package/crds/%s
provider-aws
  name: provider-aws
  version: "v0.44.2"
usePipeline: true
```

generate.yaml
```yaml
group: dms.aws.dkb.cloud
name: Endpoint
version: v1beta1
provider:
  baseURL: https://raw.githubusercontent.com/upbound/%s/%s/package/crds/%s
  name: provider-aws
  version: main
  crd:
    file: dms.aws.upbound.io_endpoints.yaml
    version: v1beta1
patchExternalName: false
defaultCompositeDeletePolicy: Foreground
compositions:
  - name: compositeendpoint.dms.aws.example
    provider: example
    default: true
```

Expected definition.yaml
```yaml
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: compositeendpoints.dms.aws.example
spec:
  defaultCompositeDeletePolicy: Foreground
  claimNames:
    kind: Endpoint
    plural: endpoints
  defaultCompositionRef:
    name: compositeendpoint.dms.aws.example
  group: dms.aws.dkb.example
```
